// Event types for Agent Tracker
// These match the schema generated by the Claude hooks

export interface ITermInfo {
  session_id: string;
  profile: string;
  tab_name: string;
  window_name: string;
}

export interface DockerInfo {
  is_container: boolean;
  container_id: string;
  container_name: string;
}

export interface TerminalInfo {
  tty: string;
  term: string;
  shell: string;
  ppid: string;
  term_program: string;
  term_session_id: string;
  lc_terminal: string;
  lc_terminal_version: string;
  iterm: ITermInfo;
}

export interface BaseEvent {
  event_type: 'session_start' | 'session_end';
  session_id: string;
  cwd: string;
  transcript_path: string;
  terminal: TerminalInfo;
  docker: DockerInfo;
  timestamp: string;
}

export interface SessionStartEvent extends BaseEvent {
  event_type: 'session_start';
}

export interface SessionEndEvent extends BaseEvent {
  event_type: 'session_end';
}

export type SessionEvent = SessionStartEvent | SessionEndEvent;

export interface EventHandler {
  onSessionStart: (event: SessionStartEvent) => void;
  onSessionEnd: (event: SessionEndEvent) => void;
  onError?: (error: Error) => void;
}
