/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as PlansFilenameRouteImport } from './routes/plans/$filename'
import { Route as SessionsSessionIdTranscriptRouteImport } from './routes/sessions/$sessionId_.transcript'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansFilenameRoute = PlansFilenameRouteImport.update({
  id: '/plans/$filename',
  path: '/plans/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdTranscriptRoute =
  SessionsSessionIdTranscriptRouteImport.update({
    id: '/sessions/$sessionId_/transcript',
    path: '/sessions/$sessionId/transcript',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plans/$filename': typeof PlansFilenameRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/plans/': typeof PlansIndexRoute
  '/sessions/$sessionId/transcript': typeof SessionsSessionIdTranscriptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans/$filename': typeof PlansFilenameRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/plans': typeof PlansIndexRoute
  '/sessions/$sessionId/transcript': typeof SessionsSessionIdTranscriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plans/$filename': typeof PlansFilenameRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/plans/': typeof PlansIndexRoute
  '/sessions/$sessionId_/transcript': typeof SessionsSessionIdTranscriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plans/$filename'
    | '/sessions/$sessionId'
    | '/plans/'
    | '/sessions/$sessionId/transcript'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plans/$filename'
    | '/sessions/$sessionId'
    | '/plans'
    | '/sessions/$sessionId/transcript'
  id:
    | '__root__'
    | '/'
    | '/plans/$filename'
    | '/sessions/$sessionId'
    | '/plans/'
    | '/sessions/$sessionId_/transcript'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlansFilenameRoute: typeof PlansFilenameRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  PlansIndexRoute: typeof PlansIndexRoute
  SessionsSessionIdTranscriptRoute: typeof SessionsSessionIdTranscriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$filename': {
      id: '/plans/$filename'
      path: '/plans/$filename'
      fullPath: '/plans/$filename'
      preLoaderRoute: typeof PlansFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId_/transcript': {
      id: '/sessions/$sessionId_/transcript'
      path: '/sessions/$sessionId/transcript'
      fullPath: '/sessions/$sessionId/transcript'
      preLoaderRoute: typeof SessionsSessionIdTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlansFilenameRoute: PlansFilenameRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  PlansIndexRoute: PlansIndexRoute,
  SessionsSessionIdTranscriptRoute: SessionsSessionIdTranscriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
