/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as SessionsSessionIdTranscriptRouteImport } from './routes/sessions/$sessionId.transcript'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdTranscriptRoute =
  SessionsSessionIdTranscriptRouteImport.update({
    id: '/transcript',
    path: '/transcript',
    getParentRoute: () => SessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/sessions/$sessionId/transcript': typeof SessionsSessionIdTranscriptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/sessions/$sessionId/transcript': typeof SessionsSessionIdTranscriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/sessions/$sessionId/transcript': typeof SessionsSessionIdTranscriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/events'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/transcript'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/events'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/transcript'
  id:
    | '__root__'
    | '/'
    | '/api/events'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/transcript'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEventsRoute: typeof ApiEventsRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/transcript': {
      id: '/sessions/$sessionId/transcript'
      path: '/transcript'
      fullPath: '/sessions/$sessionId/transcript'
      preLoaderRoute: typeof SessionsSessionIdTranscriptRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
  }
}

interface SessionsSessionIdRouteChildren {
  SessionsSessionIdTranscriptRoute: typeof SessionsSessionIdTranscriptRoute
}

const SessionsSessionIdRouteChildren: SessionsSessionIdRouteChildren = {
  SessionsSessionIdTranscriptRoute: SessionsSessionIdTranscriptRoute,
}

const SessionsSessionIdRouteWithChildren =
  SessionsSessionIdRoute._addFileChildren(SessionsSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEventsRoute: ApiEventsRoute,
  SessionsSessionIdRoute: SessionsSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
